import { useEffect, useState } from 'react';
import { Link, Route, Routes, useLocation } from 'react-router-dom';
import { motion } from 'framer-motion';
import { ArrowRight, CalendarDays, ChevronRight, Clock3, Download, Mail, MapPin, Menu, Microscope, Play, Send, Sparkles, X } from 'lucide-react';
import { dates, nav, people, tracks } from './data';

const img=(name:string)=>`/images/${name}`;

function Header(){const [open,setOpen]=useState(false);const loc=useLocation();return <><div className="topbar"><span>NC4SCM · NED University of Engineering & Technology</span><a href="mailto:conference@nc4scm.com"><Mail size={14}/> conference@nc4scm.com</a></div><header><Link className="brand" to="/"><span className="mark">NC<sup>4</sup></span><span><b>SCM ’26</b><small>LOW-CARBON FUTURES</small></span></Link><button className="menu" onClick={()=>setOpen(!open)} aria-label="Menu">{open?<X/>:<Menu/>}</button><nav className={open?'open':''}>{nav.map(([n,p])=><Link className={loc.pathname===p?'active':''} key={p} to={p} onClick={()=>setOpen(false)}>{n}</Link>)}<Link className="nav-cta" to="/registration">Register</Link></nav></header></>}

function Footer(){return <footer><div className="footer-brand"><span className="mark">NC<sup>4</sup></span><h3>SCM Conference 2026</h3><p>Advancing low-carbon construction materials through science, industry and global collaboration.</p></div><div><h4>Explore</h4>{nav.slice(1,7).map(([n,p])=><Link key={p} to={p}>{n}</Link>)}</div><div><h4>Resources</h4><Link to="/call-for-papers">Author guidelines</Link><Link to="/programme">Programme</Link><Link to="/partners">Partnership</Link><Link to="/archive">Media archive</Link></div><div><h4>Contact</h4><p>NED University, University Road<br/>Karachi, Pakistan</p><a href="mailto:conference@nc4scm.com">conference@nc4scm.com</a></div><div className="copyright">© 2026 NC4SCM. Placeholder content is clearly marked pending official confirmation.</div></footer>}

const Reveal=({children,className='' }:{children:any,className?:string})=><motion.div className={className} initial={{opacity:0,y:28}} whileInView={{opacity:1,y:0}} viewport={{once:true,amount:.15}} transition={{duration:.65}}>{children}</motion.div>;
function PageHero({eyebrow,title,copy}:{eyebrow:string,title:string,copy:string}){return <section className="page-hero"><div className="grain"/><Reveal><span className="eyebrow">{eyebrow}</span><h1>{title}</h1><p>{copy}</p></Reveal></section>}
function Button({to,children,ghost=false}:{to:string,children:any,ghost?:boolean}){return <Link className={ghost?'button ghost':'button'} to={to}>{children}<ArrowRight size={17}/></Link>}

function Home(){return <>
 <section className="hero"><div className="hero-media"><img src={img('plant-aerial.jpg')} alt="Low-carbon cement production facility"/><div className="scan"/></div><div className="hero-overlay"/><div className="hero-grid"/><div className="hero-copy"><motion.span initial={{opacity:0}} animate={{opacity:1}} className="eyebrow">INTERNATIONAL CONFERENCE · 2026 · KARACHI</motion.span><motion.h1 initial={{opacity:0,y:30}} animate={{opacity:1,y:0}} transition={{delay:.15}}>Building the<br/><em>low-carbon</em><br/>material future.</motion.h1><motion.p initial={{opacity:0}} animate={{opacity:1}} transition={{delay:.35}}>A global forum for cement science, sustainable construction and the systems reshaping our built environment.</motion.p><motion.div className="actions" initial={{opacity:0}} animate={{opacity:1}} transition={{delay:.5}}><Button to="/call-for-papers">Submit research</Button><Button to="/about" ghost>Explore conference</Button></motion.div></div><div className="hero-side"><span>Hosted by</span><b>National Centre for<br/>Sustainable Construction Materials</b><div><MapPin size={17}/> NED University, Karachi</div></div><div className="scroll-note">SCROLL TO EXPLORE <span/></div></section>
 <section className="ticker"><div>LOW-CARBON CEMENT <i>✦</i> CIRCULAR MATERIALS <i>✦</i> SUSTAINABLE CONSTRUCTION <i>✦</i> WHOLE-LIFE PERFORMANCE <i>✦</i></div></section>
 <section className="intro section"><Reveal className="intro-number">01</Reveal><Reveal><span className="eyebrow dark">THE CONFERENCE</span><h2>Where material science<br/>meets climate action.</h2></Reveal><Reveal><p>The NC4SCM Conference brings researchers, manufacturers, designers and policymakers together to accelerate measurable decarbonisation across cement and construction.</p><Button to="/about" ghost>Discover our purpose</Button></Reveal></section>
 <section className="feature-film"><img src={img('cement-trowel.jpg')} alt="Cement and masonry research"/><div className="film-shade"/><Reveal><button className="play" aria-label="Play conference film"><Play fill="currentColor"/></button><span>CONFERENCE FILM · COMING SOON</span></Reveal></section>
 <section className="tracks section"><Reveal className="section-title"><span className="eyebrow dark">09 RESEARCH DOMAINS</span><h2>Conference tracks</h2><p>A focused programme spanning chemistry, engineering, circularity, modelling and economics.</p></Reveal><div className="track-list">{tracks.map(([n,t,d])=><Reveal className="track" key={n}><b>{n}</b><h3>{t}</h3><p>{d}</p><ChevronRight/></Reveal>)}</div></section>
 <section className="metrics"><div><b>09</b><span>Research tracks</span></div><div><b>2026</b><span>Conference edition</span></div><div><b>Global</b><span>Academic + industry exchange</span></div><div><b>Karachi</b><span>Hosted at NED University</span></div></section>
 <section className="dates section"><Reveal><span className="eyebrow">PLAN YOUR SUBMISSION</span><h2>Important<br/>dates.</h2><p>Milestones are prepared as editable placeholders until the secretariat confirms the official calendar.</p></Reveal><div>{dates.map(([t,d],i)=><Reveal className="date-row" key={t}><span>0{i+1}</span><h3>{t}</h3><b>{d}</b><CalendarDays/></Reveal>)}</div></section>
 <section className="gallery-strip"><img src={img('plant-green.jpg')} alt="Cement plant landscape"/><img src={img('concrete-work.jpg')} alt="Concrete construction"/><img src={img('silos.jpg')} alt="Cement silos"/><div><span>FIELD / LAB / INDUSTRY</span><h2>From research to real-world impact.</h2><Button to="/archive">View media archive</Button></div></section>
 <CTA/></>}

function CTA(){return <section className="cta"><Sparkles/><span className="eyebrow">JOIN THE CONVERSATION</span><h2>Shape what gets built next.</h2><p>Submit your research, attend as a delegate or partner with NC4SCM Conference 2026.</p><div className="actions"><Button to="/call-for-papers">Submit a paper</Button><Button to="/registration" ghost>Register interest</Button></div></section>}

function About(){return <><PageHero eyebrow="ABOUT NC4SCM ’26" title="Science for a built world within limits." copy="A conference designed around credible research, industrial relevance and collaborative climate action."/><section className="split section"><Reveal><span className="eyebrow dark">WHY THIS CONFERENCE</span><h2>Construction must change. Together, it can.</h2></Reveal><Reveal><p>Concrete is foundational to modern life. Its transition demands new binders, cleaner processes, durable circular materials and evidence-led decisions. NC4SCM ’26 creates the room where those disciplines connect.</p><p className="muted">Official conference overview, edition history and hosting-partner language will be inserted after approval.</p></Reveal></section><section className="values section">{['Research integrity','Industrial relevance','Climate accountability','Open collaboration'].map((x,i)=><Reveal className="value" key={x}><b>0{i+1}</b><Microscope/><h3>{x}</h3><p>Placeholder statement prepared for the official organizing team’s approved content.</p></Reveal>)}</section><section className="journey section"><span className="eyebrow">CONFERENCE JOURNEY</span><h2>Built to become a lasting platform.</h2>{['Foundation of NC4SCM','First conference edition','Regional research network','International low-carbon forum'].map((x,i)=><div className="journey-row" key={x}><b>{2023+i}</b><span>{x}</span><p>Milestone details to be confirmed.</p></div>)}</section><CTA/></>}

function Speakers(){return <><PageHero eyebrow="VISIONARY MINDS" title="Speakers shaping material futures." copy="Keynote speakers, plenary guests and industry voices will appear here as they are confirmed."/><section className="section"><div className="filter"><button>All</button><button>Keynote</button><button>Plenary</button><button>Industry</button></div><div className="speaker-grid">{[1,2,3,4,5,6].map(n=><Reveal className="speaker placeholder" key={n}><div className="portrait"><span>ANNOUNCEMENT<br/>COMING SOON</span></div><small>KEYNOTE SPEAKER</small><h3>Speaker name</h3><p>Institution · Country</p></Reveal>)}</div></section><CTA/></>}

function CallForPapers(){return <><PageHero eyebrow="CALL FOR PAPERS" title="Research with real-world consequence." copy="We invite original research advancing low-carbon construction materials, systems and practice."/><section className="split section"><Reveal><h2>Original thinking.<br/>Measurable impact.</h2></Reveal><Reveal><p>Authors are invited to submit rigorous theoretical, experimental, computational and applied work aligned with the conference tracks.</p><div className="paper-type"><b>FULL PAPER</b><span>Page length · To be confirmed</span></div><div className="paper-type"><b>EXTENDED ABSTRACT</b><span>Availability · To be confirmed</span></div></Reveal></section><section className="tracks section alt"><span className="eyebrow dark">AREAS OF INTEREST</span><h2>Research tracks</h2><div className="track-list compact">{tracks.map(([n,t,d])=><div className="track" key={n}><b>{n}</b><h3>{t}</h3><p>{d}</p></div>)}</div></section><section className="guide section"><h2>Submission guidelines</h2>{[['FORMAT','Official template to be provided'],['LENGTH','To be confirmed'],['SYSTEM','Submission portal to be confirmed'],['REVIEW','Peer-review process to be confirmed'],['PUBLICATION','Proceedings information to be confirmed']].map(x=><div><b>{x[0]}</b><span>{x[1]}</span></div>)}<button className="button disabled"><Download size={17}/> Download author template</button></section><CTA/></>}

function Programme(){return <><PageHero eyebrow="CONFERENCE PROGRAMME" title="Two days of ideas, evidence and exchange." copy="The programme framework is ready; sessions and timings will be published after confirmation."/><section className="section programme"><div className="tabs"><button>Day 01</button><button>Day 02</button></div>{['Registration & welcome','Opening plenary','Technical sessions — parallel tracks','Industry dialogue','Networking & poster exchange'].map((x,i)=><Reveal className="session"><span><Clock3/> {String(9+i*2).padStart(2,'0')}:00</span><div><small>{i===2?'PARALLEL PROGRAMME':'MAIN HALL'}</small><h3>{x}</h3><p>Session details and speakers to be announced.</p></div></Reveal>)}</section></>}
function Workshops(){return <><PageHero eyebrow="PRACTICE + APPLICATION" title="Workshops built for doing." copy="Hands-on sessions will translate new methods and evidence into practical capability."/><section className="section workshop-grid">{['Alternative binder design','Life-cycle assessment lab','Advanced material characterization','Digital modelling studio'].map((x,i)=><Reveal className="workshop"><span>WORKSHOP 0{i+1}</span><h3>{x}</h3><p>Facilitator, audience, capacity and learning outcomes to be confirmed.</p><div><CalendarDays/> Schedule pending</div></Reveal>)}</section><CTA/></>}
function Registration(){return <><PageHero eyebrow="ATTEND NC4SCM ’26" title="Register your interest." copy="Registration categories and approved fees will be published by the conference secretariat."/><section className="section price-grid">{['Early bird','Standard','Student','Workshop only'].map((x,i)=><Reveal className={i===0?'price featured':'price'}><span>{i===0?'RECOMMENDED':'REGISTRATION'}</span><h3>{x}</h3><b>Fee TBC</b><p>Access package and eligibility details to be confirmed.</p><ul><li>Conference sessions</li><li>Digital programme</li><li>Networking access</li><li>Certificate policy TBC</li></ul><button className="button disabled">Opening soon</button></Reveal>)}</section><section className="guide section"><h2>Registration policies</h2>{['Payment method','Cancellation policy','Author registration rule','International delegate guidance'].map(x=><div><b>{x}</b><span>Official information required</span></div>)}</section></>}
function Committees(){return <><PageHero eyebrow="PEOPLE BEHIND THE CONFERENCE" title="Committees and governance." copy="The structure is prepared for patronage, advisory, organizing and technical committees."/><section className="section"><div className="people-grid">{people.map((role,i)=><Reveal className="person"><div>{String(i+1).padStart(2,'0')}</div><small>{role}</small><h3>Name to be confirmed</h3><p>NED University of Engineering & Technology</p></Reveal>)}</div><h2 className="subhead">International advisory board</h2><div className="people-grid">{[1,2,3,4,5,6].map(i=><Reveal className="person"><div>AB</div><small>ADVISORY MEMBER</small><h3>Name to be confirmed</h3><p>Institution · Country</p></Reveal>)}</div></section></>}
function Partners(){return <><PageHero eyebrow="PARTNERSHIP" title="Accelerate change with us." copy="Partner with a high-trust forum connecting research, policy and materials industry leadership."/><section className="metrics"><div><b>Research</b><span>Academic visibility</span></div><div><b>Industry</b><span>Applied exchange</span></div><div><b>Policy</b><span>Strategic dialogue</span></div><div><b>Talent</b><span>Future capability</span></div></section><section className="section price-grid">{['Principal partner','Innovation partner','Supporting partner'].map(x=><Reveal className="price"><span>PARTNERSHIP TIER</span><h3>{x}</h3><p>Benefits, recognition, delegate access and activation options to be confirmed.</p><Button to="/contact" ghost>Request information</Button></Reveal>)}</section></>}
function Archive(){return <><PageHero eyebrow="MEDIA + PAST EDITIONS" title="The conference archive." copy="A home for editions, proceedings, galleries, films and conference outcomes."/><section className="section archive-grid">{[['2026','Current edition','plant-aerial.jpg'],['2025','Source materials','concrete-work.jpg'],['Future','Proceedings archive','silos.jpg']].map(x=><Reveal className="archive-card"><img src={img(x[2])}/><span>{x[0]}</span><h3>{x[1]}</h3><p>Gallery, reports and edition details will appear here.</p></Reveal>)}</section></>}
function Contact(){return <><PageHero eyebrow="CONTACT THE SECRETARIAT" title="Start a conversation." copy="Questions about papers, registration, partnership or participation? Use the relevant contact route below."/><section className="contact section"><div><span className="eyebrow dark">CONTACT INFORMATION</span><h2>NC4SCM Conference Secretariat</h2><p><MapPin/> NED University of Engineering & Technology<br/>University Road, Karachi, Pakistan</p><p><Mail/> conference@nc4scm.com <small>placeholder</small></p></div><form onSubmit={e=>e.preventDefault()}><label>Name<input placeholder="Your full name"/></label><label>Email<input type="email" placeholder="you@example.com"/></label><label>Subject<select><option>General enquiry</option><option>Paper submission</option><option>Registration</option><option>Partnership</option></select></label><label>Message<textarea rows={5} placeholder="How can we help?"/></label><button className="button disabled"><Send size={17}/> Form activation pending</button></form></section></>}

function App(){const loc=useLocation();useEffect(()=>window.scrollTo(0,0),[loc.pathname]);return <><Header/><main><Routes><Route path="/" element={<Home/>}/><Route path="/about" element={<About/>}/><Route path="/speakers" element={<Speakers/>}/><Route path="/call-for-papers" element={<CallForPapers/>}/><Route path="/programme" element={<Programme/>}/><Route path="/workshops" element={<Workshops/>}/><Route path="/registration" element={<Registration/>}/><Route path="/committees" element={<Committees/>}/><Route path="/partners" element={<Partners/>}/><Route path="/archive" element={<Archive/>}/><Route path="/contact" element={<Contact/>}/><Route path="*" element={<Home/>}/></Routes></main><Footer/></>}
export default App;
